#!/bin/bash

cp -f ./Esquemas_de_Configuracion/Esquema1/lru.conf ./MSP/config/lru.conf
cp -f ./Esquemas_de_Configuracion/Esquema1/clock.conf ./MSP/config/clock.conf
cp -f ./Esquemas_de_Configuracion/Esquema1/kernel.conf ./Kernel/config/kernel.conf
