#!/bin/bash
for f in $(find ./ESO/* -name '*.txt' -print); do
	echo $f $(./build/so-ensamblador -o ${f%.txt}.bc $f)
	mv ${f%.txt}.bc ../Consola/BESO
	aux=${f/.txt/Console}
	name=${aux:6}
	file="../Consola/"$name
	touch $file
	echo -e "#!/bin/bash\nclear\n./bin/Consola BESO/"$name > $file
	chmod +x $file
done